apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgre-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: /data/hudo/kubernets-volumes/postgre-volume/
